# Generated by Django 3.0.8 on 2020-07-07 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200707_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_required',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_required',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
