# Generated by Django 3.0.8 on 2020-07-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
    ]
