# Generated by Django 3.0.8 on 2020-07-08 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(14), django.core.validators.MinLengthValidator(9)]),
        ),
    ]
