# Generated by Django 3.0.8 on 2020-07-08 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200708_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999999999999), django.core.validators.MinValueValidator(100000000)]),
        ),
    ]
