# Generated by Django 3.0.8 on 2020-07-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='icon',
        ),
    ]
