# Generated by Django 3.0.8 on 2020-07-08 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200708_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999999999999), django.core.validators.MinValueValidator(100000000)]),
        ),
    ]
