# Generated by Django 3.0.8 on 2020-07-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200703_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post_code',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
